# Generated by Django 3.0.7 on 2020-06-25 01:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_task', '0002_auto_20200625_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
