# Generated by Django 3.0.7 on 2020-06-25 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_task', '0003_auto_20200625_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upvote',
            field=models.ManyToManyField(related_name='users_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
